# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb2.hello2 import hello_dto_pb2 as hello__dto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello2',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x06hello2\x1a\x0fhello-dto.proto2A\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.hello2.HelloRequest\x1a\x12.hello2.HelloReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
  ,
  dependencies=[hello__dto__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='hello2.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=40,
  serialized_end=105,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hello2.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=hello__dto__pb2._HELLOREQUEST,
    output_type=hello__dto__pb2._HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
