# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_app.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb2.hello import hello_dto_pb2 as hello__dto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_app.proto',
  package='hello',
  syntax='proto3',
  serialized_options=b'\n\thello_app\210\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fhello_app.proto\x12\x05hello\x1a\x0fhello_dto.proto2G\n\x07Greeter\x12<\n\x08SayHello\x12\x17.hello_dto.HelloRequest\x1a\x15.hello_dto.HelloReply\"\x00\x42\x0e\n\thello_app\x88\x01\x01\x62\x06proto3'
  ,
  dependencies=[hello__dto__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='hello.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=43,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hello.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=hello__dto__pb2._HELLOREQUEST,
    output_type=hello__dto__pb2._HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
